### Numpy ndarray 개요

In [2]:
import numpy as np # 패키지 불러오기

ndarray: N차원 배열(array)객체

In [4]:
# 배열 3가지 형성
array1 = np.array([1,2,3])
print('array1 type:',type(array1)) # type 확인
print('array1 array 형태:',array1.shape) # 행과 열의 갯수 확인

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2)) # type 확인
print('array2 array 형태:',array2.shape) # 행과 열의 갯수 확인

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3)) # type 확인
print('array3 array 형태:',array3.shape) # 행과 열의 갯수 확인

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim)) # 차원 확인

array1: 1차원, array2: 2차원, array3:  2차원


In [9]:
list1 = [1,2,3] 
print(type(list1)) # type확인: list
array1 = np.array(list1)
print(type(array1)) # type확인: numpy.ndarray
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [10]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # dtype: <U11(문자열 형태)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # dtype: float64(실수 형태)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [11]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # type 실수형으로 지정하기
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32') # type 정수로 지정하기
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32') # type 정수로 지정하기
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
sequence_array = np.arange(10) # 정수 순서대로 10개 생성
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)



[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [12]:
zero_array = np.zeros((3,2),dtype='int32') # 0의 값을 갖는 3행 2열인 배열 생성
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) # 1의 값을 갖는 3행 2열인 배열 생성
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [15]:
array1 = np.arange(10) # 정수값 순서대로 10개까지 생성
print('array1:\n', array1)

array2 = array1.reshape(2,5) # 2행 5열로 재배열
print('array2:\n',array2)

array3 = array1.reshape(5,2) # 5행 2열로 재배열
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1.reshape(4,3) # 값이 10개라 불가함

ValueError: cannot reshape array of size 10 into shape (4,3)

In [19]:
array1 = np.arange(10) # 정수값 순서대로 10개까지 생성
print(array1)

array2 = array1.reshape(-1,5) # 2행 5열로 재배열
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1) # 5행 2열로 재배열
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [20]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 숫자가 10개이므로, 2행 4열은 불가함.

ValueError: cannot reshape array of size 10 into shape (4)

In [22]:
array1 = np.arange(8) # 정수값 순서대로 8개까지 생성
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### indexing

* 단일값 추출

In [23]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2] # 2위치에 있는 값 추출
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [24]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2]) # 맨 뒤의 값, 맨 뒤에서 두번째 값 추출

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [25]:
array1[0] = 9 # 0번째 자리 9값으로 변경
array1[8] = 0 # 8번재 자리 0값으로 변경
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3행 3열로 재배열
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] ) # 각 행,열 위치에 있는 값 추출
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [30]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] #0부터 2위치에 있는 값까지 추출
print(array3)
print(type(array3)) # type확인

[1 2 3]
<class 'numpy.ndarray'>


In [31]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # ~ 2위치에 있는 값까지 추출
print(array4)

array5 = array1[3:] # 3위치에 있는 값부터 추출
print(array5)

array6 = array1[:] # 모두 추출
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [32]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3행 3열로 재배열
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2]) # 0부터 1까지 행 중에서 0부터 1까지 열 값 추출
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3]) # 1부터 2까지 행 중에서 0부터 2까지 열 값 추출
print('array2d[1:3, :] \n', array2d[1:3, :]) # 1부터 2까지 행인 모든 열 추출
print('array2d[:, :] \n', array2d[:, :]) # 모두 추출
print('array2d[:2, 1:] \n', array2d[:2, 1:]) # ~ 1행까지 중에서 1열부터~ 해당하는 거 추출
print('array2d[:2, 0] \n', array2d[:2, 0]) # ~ 1행까지 중에서 0인 열 추출

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [33]:
print(array2d[0]) # 0행 추출
print(array2d[1]) # 1행 추출
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [36]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3) # 3행 3열로 재배열

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist()) # 0과1행의 2위치의 열의 값 추출

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist()) # 0과1행의 1위치까지의 열의 값 추출

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist()) # 0과1행값 추출

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [37]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5] # 5보다 큰 값 추출
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [38]:
array1d > 5 # 5보다 큰 값이면 True

array([False, False, False, False, False,  True,  True,  True,  True])

In [39]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes] # True인 값만 저장
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [42]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ] # array1d에서 5,6,7,8번째에 위치한 값들만 저장
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [43]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)  # 오름차순으로 정렬하기       
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort() 
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2) # None
print('org_array.sort( ) 호출 후 원본 행렬:', org_array) #[1 3 5 9]

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [44]:
sort_array1_desc = np.sort(org_array)[::-1] # 내림차순으로 정렬하기
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [45]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0) # 행 방향으로 오름차순
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) # 열방향으로 오름차순
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [31]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array) # 원본 행렬의 인덱스 값 저장
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [46]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1] # 원본 행렬의 인덱스 값 저장
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [47]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array) # 성적 원본 행렬의 인덱스 값 저장
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) # 오름차순으로 해당하는 이름 추출

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [48]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B) # A와 B의 내적 값 구하기
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [49]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A) # A읠 전치 행렬 구하기
print('A의 전치 행렬:\n', transpose_mat) 

A의 전치 행렬:
 [[1 3]
 [2 4]]
